[build]
target = "xtensa-esp32-espidf"
# https://github.com/esp-rs/rust-build/issues/70
rustflags = "--cfg espidf_time64"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_VERSION = { value = "tag:v5.1.2" }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults;sdkconfig.defaults.esp32" }
